trigger:
  batch: true
  branches:
    include: 
    - main
  paths:
    include: 
    - charts/tpm-library/*

pr:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: majorVersion
    value: '0'
  - name: minorVersion
    value: '1'
  - name: patchVersion
    value: $[counter(format('{0}.{1}',variables['majorVersion'],variables['minorVersion']),0)]
  - name: buildNumber
    value: $(majorVersion).$(minorVersion).$(patchVersion)

stages:
- stage: Prereqs
  displayName: Prerequisites
  jobs:
    - job: UpdateBuildNumber
      displayName: Update Build Number
      steps:
      # Updates the build number in Azure DevOps (requires refresh in the UI to see)
      - bash: |
          echo '##vso[build.updatebuildnumber]$(buildNumber)'
        displayName: Update build number

- stage: LintTest
  displayName: Lint and Test
  jobs:
    - job: LintTestChart
      displayName: Lint and Test Helm Chart
      steps:
      - template: .azure-pipelines/templates/steps/lint-test.yaml
        parameters:
          chartName: tpm-library-testing
          chartPath: $(Build.SourcesDirectory)/tests/